name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git diff to work properly

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tomli

      - name: Check version bump
        run: |
          # Get the current version from main branch
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:pyproject.toml | python -c "import tomli; import sys; print(tomli.load(sys.stdin)['project']['version'])")
          
          # Get the version from the PR
          PR_VERSION=$(python -c "import tomli; import sys; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")
          
          # Compare versions
          if [ "$MAIN_VERSION" = "$PR_VERSION" ]; then
            echo "Error: Version must be bumped in pyproject.toml before merging to main"
            echo "Current version: $MAIN_VERSION"
            exit 1
          fi
          
          echo "Version check passed: $MAIN_VERSION -> $PR_VERSION" 