name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install coverage-badge
        
    - name: Run first set of tests
      run: |
        pytest --ignore=tests/test_contract.py --ignore=tests/test_cli.py --cov=data_sitter
        
    - name: Run second set of tests
      run: |
        pytest tests/test_contract.py tests/test_cli.py --cov=data_sitter --cov-append
        
    - name: Generate coverage report
      run: |
        coverage xml
        coverage json
        coverage report
        coverage-badge -o coverage.svg -f

    - name: Upload coverage report to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          coverage.xml
          coverage.json
          coverage.svg

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false

    - name: Commit coverage badge to PR branch
      if: github.event_name == 'pull_request'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update coverage badge"
        file_pattern: coverage.svg
        branch: ${{ github.head_ref }}
